services:
  - type: web
    name: ecommerce-project
    env: php
    plan: free
    buildCommand: "composer install && php artisan key:generate"
    startCommand: "php artisan serve --host=0.0.0.0 --port=10000"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:PLACE_YOUR_APP_KEY_HERE
    autoDeploy: true
    rootDir: .
